### ISSUE TITLE
Downloaded Code shows Virus on scanning

### ISSUE THREAD

**Issue by ascyrax** [greyhatguy007/deep-learning-specialization#1]
Hi Ritwick, When I downloaded your code for the deep-learning-specialization, i could not unzip the file because windows defender automatically deleted it. It showed that the zip file had some kind of trojan or virus. Can you please look in to this matter?

**Comment by greyhatguy007** [comment]
This is a well known issue. MS apparently flags most zip files off GitHub as threat (idk why).  Try disabling AV or just clone the repo.
